### ISSUE TITLE
Recursive Fibonacci returning incorrect value

### ISSUE THREAD

**Issue by ghost** [HassiumTeam/Hassium#30]
The following code prints '-12' while it should print 144. At first I thought this was an arithmetic overflow, but I verified its not. This may be related to https://github.com/HassiumTeam/Hassium/issues/27 which has not been resolved yet.

```
func fib (n) {
    if (n < 2) {
        return n;
    }
    return fib (n - 2) + fib (n - 1);
}


func main () {
        print (fib (12));
}
```

**Comment by zdimension** [comment]
Fixed with https://github.com/HassiumTeam/Hassium/commit/84ff62709af54fcabe47e72c74eda037cd4b460c.
