### ISSUE TITLE
Local variables are not local

### ISSUE THREAD

**Issue by ghost** [HassiumTeam/Hassium#31]
I believe this is the source of problem that caused https://github.com/HassiumTeam/Hassium/issues/27 and https://github.com/HassiumTeam/Hassium/issues/30 respectively.

**Problem**

Every function call should allocate its own set of locals on the stack, and this includes recursive calls. This however does not apply to Hassium in specific scenarios.  This is shown in the following example

```
func recursionTest (c) {
    if (c = 5) {
        println (c);
        recursionTest (c + 1);
        println (c);
        recursionTest (c + 1);
        println (c);
    }
    return 0;
}

func main () {
    recursionTest (5);
}
```

This code should produce the output of

```
5
5
5
```

however instead it yields

```
5
6
6
```

This problem must be the result of `recursionTest (c + 1)` which apparently modifies the value of c in its parent function.

**Comment by zdimension** [comment]
Fixed with https://github.com/HassiumTeam/Hassium/commit/84ff62709af54fcabe47e72c74eda037cd4b460c.
