### ISSUE TITLE
Add suport of static members on classes

### ISSUE THREAD

**Issue by zdimension** [HassiumTeam/Hassium#33]
So you can do something like

``` go
clr = new Color(123, 123, 123);
clr.red (non-static member)
```

and : 

``` go
grad = Color.makeGradient(Colors.red, Colors.blue); (static members)
```

We would probably need to change the way constructors are implemented, but it should work better.

**Comment by JacobMisirian** [comment]
The latest sets of commits that constitute Hassium 2.x allow for static methods to builtin classes. Check out the Thread class: https://github.com/HassiumTeam/Hassium/blob/master/src/Hassium/Runtime/StandardLibrary/Types/HassiumThread.cs
