### ISSUE TITLE
Broken switch cases

### ISSUE THREAD

**Issue by MSigma** [HassiumTeam/Hassium#34]
The predicates in switch cases are incorrectly XAND'ed with the switch predicate instead of being compared. The third argument to Emit at Line 641 in HassiumCompiler.cs should be 9 instead of 8 to fix the issue. Currently unable to PR, but just thought I'd let you know.

**Comment by JacobMisirian** [comment]
I'm sorry about not replying to this sooner. I've just did a full rewrite of Hassium that closed and solved the issue with switch case statements.
